id: P000699
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 2021-12-16 16:37:44.812062
source_metadata:
  id: bdr:W3CN5300
  title: རེ་བའི་ས་བོན།
  author: ''
  volumes:
    8a7e75bff45f42ac96a64417f0c8d63f:
      image_group_id: I3CN5302
      title: ''
      volume_number: 1
      total_pages: 149
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
